import { useEffect, useState, type CSSProperties } from 'react';
import { motion, useReducedMotion } from 'framer-motion';
import { DeckFrame, Panel, Label, NumberBadge, AnimatedGroup, colors, fonts } from './deck';
import type { TeachingSlide, TeachingItem } from '../data/course';
const palette=[colors.red,colors.blue,colors.purple,colors.green];
const button:CSSProperties={fontFamily:fonts.body,fontSize:20,fontWeight:800,border:`2px solid ${colors.dark}`,borderRadius:12,padding:'9px 20px',background:colors.yellow,color:colors.dark,cursor:'pointer'};
function CopyPrompt({text}:{text:string}){const [message,setMessage]=useState('复制提示词');return <button style={button} onClick={async()=>{try{await navigator.clipboard.writeText(text);setMessage('已复制');}catch{setMessage('请选中文字复制');}}}>{message}</button>}
function Foot({slide:s}:{slide:TeachingSlide}){return <div style={{display:'flex',gap:20,alignItems:'center',marginTop:18,minHeight:28}}>{s.callout&&<p data-fit style={{fontSize:23,lineHeight:1.5,fontWeight:650,flex:1,borderLeft:`5px solid ${colors.purple}`,paddingLeft:17}}>{s.callout}</p>}{s.source&&<a href={s.source} target="_blank" rel="noopener noreferrer" style={{fontSize:17,color:colors.dark,textUnderlineOffset:4,whiteSpace:'nowrap'}}>官方资料 ↗</a>}</div>}
function Items({items,numbered=false}:{items:TeachingItem[];numbered?:boolean}){return <div>{items.map((item,i)=><div key={item.label} data-fit style={{display:'flex',alignItems:'flex-start',gap:22,padding:'19px 0',borderBottom:i===items.length-1?'none':`1px solid ${colors.dark}30`}}>{numbered&&<NumberBadge bg={palette[i%4]}>{i+1}</NumberBadge>}<strong style={{fontSize:27,lineHeight:1.45,minWidth:150,color:['#c43b3b','#176da0','#853893','#397c29'][i%4]}}>{item.label}</strong><span style={{fontSize:28,lineHeight:1.5,whiteSpace:'pre-line'}}>{item.text}</span></div>)}</div>}
function Table({slide:s}:{slide:TeachingSlide}){return <Panel style={{padding:'20px 26px',boxShadow:`8px 8px 0 ${colors.blue}`}}><table data-fit style={{width:'100%',borderCollapse:'collapse',fontSize:s.number>=41?23:25,lineHeight:1.45}}><thead><tr>{s.headers?.map(h=><th key={h} style={{textAlign:'left',padding:'13px 16px',borderBottom:`2px solid ${colors.dark}`,fontSize:22,color:'#904131'}}>{h}</th>)}</tr></thead><tbody>{s.rows?.map((row,i)=><tr key={i}>{row.map((v,j)=><td key={j} style={{padding:s.number>=41?'13px 16px':'17px 16px',borderBottom:i===(s.rows?.length??0)-1?'none':`1px solid ${colors.dark}30`,fontWeight:j===0?800:500,verticalAlign:'top',width:j===0?(s.number>=41?'33%':'20%'):undefined}}>{v}</td>)}</tr>)}</tbody></table></Panel>}
function Code({text}:{text:string}){return <pre data-fit style={{whiteSpace:'pre-wrap',fontFamily:fonts.mono,fontSize:23,lineHeight:1.65,margin:0,color:colors.dark}}>{text}</pre>}
function Timeline({slide:s}:{slide:TeachingSlide}){
 const [time,setTime]=useState(0),[playing,setPlaying]=useState(false);const reduced=useReducedMotion();
 useEffect(()=>{if(!playing)return;let previous=performance.now(),handle=0;const tick=(now:number)=>{const delta=(now-previous)/1000;previous=now;setTime(t=>{if(t+delta>=30){setPlaying(false);return 30}return t+delta});handle=requestAnimationFrame(tick)};handle=requestAnimationFrame(tick);return()=>cancelAnimationFrame(handle)},[playing]);
 const active=Math.min(3,Math.floor(time/7.5));return <div><div data-fit style={{display:'grid',gridTemplateColumns:'170px 1fr',alignItems:'center',gap:16,marginBottom:18}}><Label bg={colors.dark}>示意 · {time.toFixed(1)} s</Label><div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12}}>{s.lanes?.[0].slice(1).map((_,i)=><span key={i} style={{fontSize:23,fontWeight:800,color:active===i?colors.red:colors.dark}}>{i*7.5}–{(i+1)*7.5}s</span>)}</div></div><Panel style={{padding:20,boxShadow:`8px 8px 0 ${colors.purple}`}}>{s.lanes?.map((lane,i)=><div key={lane[0]} style={{display:'grid',gridTemplateColumns:'150px repeat(4,1fr)',gap:14,alignItems:'center',marginBottom:i===s.lanes!.length-1?0:12}}><b style={{fontSize:26}}>{lane[0]}</b>{lane.slice(1).map((x,j)=><motion.div key={j} data-fit animate={{backgroundColor:j===active?palette[i%4]:'#fff5ec',opacity:j===active?1:.66}} transition={{duration:reduced?0:.2}} style={{padding:'10px 16px',borderRadius:16,border:`1.5px solid ${colors.dark}`,fontSize:24,fontWeight:j===active?800:600,lineHeight:1.4,minHeight:56,color:colors.dark}}>{x}</motion.div>)}</div>)}</Panel><div style={{display:'flex',gap:24,alignItems:'center',marginTop:18}}><button style={button} onClick={()=>{if(time>=30)setTime(0);setPlaying(!playing)}}>{playing?'暂停':'播放教具'}</button><input aria-label="时间线位置" type="range" min={0} max={30} step={.1} value={time} onKeyDown={e=>e.stopPropagation()} onChange={e=>{setPlaying(false);setTime(Number(e.target.value))}} style={{flex:1,accentColor:colors.red}}/><span style={{fontSize:19}}>合成时间线 · 非 MP4</span></div></div>
}
function FrameDemo({slide:s}:{slide:TeachingSlide}){const [frame,setFrame]=useState(0),progress=Math.min(1,frame/30);return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:26}}><Panel style={{padding:28,boxShadow:`8px 8px 0 ${colors.blue}`}}><Label bg={colors.blue} color={colors.dark}>逻辑片段</Label><div style={{marginTop:25}}><Code text={s.text??''}/></div><p style={{fontSize:20,lineHeight:1.6,marginTop:18}}>在已配置的 React composition 内运行。</p></Panel><Panel style={{padding:30,boxShadow:`8px 8px 0 ${colors.red}`}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><Label bg={colors.yellow} color={colors.dark}>帧号教具</Label><span style={{fontFamily:fonts.mono,fontSize:30}}>f {frame}</span></div><div style={{height:205,display:'flex',alignItems:'center',justifyContent:'center'}}><h2 data-testid="frame-title" style={{opacity:progress,fontSize:44,textAlign:'center',lineHeight:1.3}}>让客户<br/>自己选择时间</h2></div><input aria-label="当前帧号" type="range" min={0} max={60} value={frame} onKeyDown={e=>e.stopPropagation()} onChange={e=>setFrame(Number(e.target.value))} style={{width:'100%',accentColor:colors.red}}/><p style={{fontSize:24,marginTop:15}}>opacity = {progress.toFixed(2)}</p><p style={{fontSize:18,lineHeight:1.5,marginTop:12}}>课件模拟帧号逻辑；不是 Remotion 导出。</p></Panel></div>}
function Content({slide:s}:{slide:TeachingSlide}){
 if(s.kind==='timeline')return <Timeline slide={s}/>;
 if(s.kind==='frame')return <FrameDemo slide={s}/>;
 if(s.kind==='cover')return <div style={{display:'grid',gridTemplateColumns:'1.1fr .9fr',gap:44,alignItems:'center',height:450}}><div><Label bg={colors.yellow} color={colors.dark}>AI VIDEO · FOUNDER</Label><h2 data-fit style={{fontFamily:fonts.heading,fontSize:74,lineHeight:1.14,marginTop:28}}>先有声音，<br/>再让画面<br/><span style={{color:colors.red}}>跟着内容动。</span></h2><p style={{fontSize:24,marginTop:25,lineHeight:1.5}}>{s.highlight}</p></div><Panel style={{transform:'rotate(-2deg)',boxShadow:`12px 12px 0 ${colors.blue}`,padding:34}}><Items items={s.items} numbered/></Panel></div>;
 if(s.kind==='table'||s.kind==='script')return <Table slide={s}/>;
 if(s.kind==='prompt')return <Panel style={{padding:'26px 32px',boxShadow:`9px 9px 0 ${colors.purple}`}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><Label bg={colors.purple}>可复制任务</Label><CopyPrompt text={s.text??''}/></div><div data-fit style={{fontFamily:fonts.body,fontSize:25,lineHeight:1.65,whiteSpace:'pre-wrap',userSelect:'text'}}>{s.text}</div></Panel>;
 if(s.kind==='code')return <div style={{display:'grid',gridTemplateColumns:'1.12fr .88fr',gap:30}}><Panel style={{padding:32,boxShadow:`9px 9px 0 ${colors.blue}`}}><Code text={s.text??''}/></Panel><div style={{padding:'0 15px'}}><Items items={s.items}/></div></div>;
 if(s.kind==='compare')return <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:28}}>{[[s.leftTitle,s.left],[s.rightTitle,s.right]].map(([title,text],i)=><AnimatedGroup key={title} delay={.15+i*.1}><Panel style={{padding:32,boxShadow:`9px 9px 0 ${palette[i]}`,minHeight:320}}><Label bg={palette[i]} color={colors.dark}>{title}</Label><p data-fit style={{fontSize:32,fontWeight:i===1?750:500,lineHeight:1.65,whiteSpace:'pre-line',marginTop:30}}>{text}</p></Panel></AnimatedGroup>)}</div>;
 if(s.kind==='flow'||s.kind==='tiles')return <div style={{display:'flex',gap:s.kind==='flow'?20:26,alignItems:'stretch',paddingTop:25}}>{s.items.map((x,i)=><AnimatedGroup key={x.label} delay={i*.12} style={{flex:1}}><Panel style={{minHeight:s.kind==='flow'?270:310,padding:28,boxShadow:`8px 8px 0 ${palette[i%4]}`}}><NumberBadge bg={palette[i%4]}>{i+1}</NumberBadge><h2 style={{fontSize:32,lineHeight:1.4,marginTop:24,marginBottom:18}}>{x.label}</h2><p data-fit style={{fontSize:26,lineHeight:1.55}}>{x.text}</p></Panel></AnimatedGroup>)}</div>;
 if(s.kind==='demo')return <div style={{display:'grid',gridTemplateColumns:'.75fr 1.25fr',gap:28}}><Panel style={{padding:33,background:colors.yellow,boxShadow:`9px 9px 0 ${colors.red}`}}><Label>LIVE DEMO</Label><h2 style={{fontSize:48,lineHeight:1.2,marginTop:40}}>同一份内容，<br/>看画面<br/>如何产生。</h2><p style={{fontSize:23,lineHeight:1.55,marginTop:24}}>打开讲师准备的真实工程；失败时使用明确标注的预制样本。</p></Panel><Items items={s.items}/></div>;
 if(s.kind==='sound')return <div style={{display:'grid',gridTemplateColumns:'.7fr 1.3fr',gap:32}}><Panel style={{padding:26,boxShadow:`8px 8px 0 ${colors.blue}`}}><Label bg={colors.blue} color={colors.dark}>听觉优先级</Label><div style={{marginTop:22}}>{[['旁白',95,colors.red],['音乐',35,colors.purple],['环境声',20,colors.blue]].map(([label,w,c])=><div key={String(label)} style={{marginBottom:18}}><b style={{fontSize:27}}>{label}</b><div style={{height:20,marginTop:12,width:`${w}%`,borderRadius:10,background:String(c)}}/></div>)}</div><p style={{fontSize:19,lineHeight:1.6}}>关系示意，不是推荐音量数值。</p></Panel><Items items={s.items}/></div>;
 return <Panel style={{padding:'12px 32px',boxShadow:`8px 8px 0 ${s.kind==='brief'?colors.green:colors.yellow}`}}><Items items={s.items} numbered={s.kind==='steps'||s.kind==='checklist'}/></Panel>;
}
export default function TeachingContent({slide:s}:{slide:TeachingSlide}){return <section data-slide={s.number} style={{width:'100%',height:'100%',color:colors.dark,fontFamily:fonts.body}}><DeckFrame tag={s.chapter} title={s.title} subtitle={s.subtitle} accent={palette[Math.floor((s.number-1)/6)%4]} titleSize={s.kind==='cover'?62:56}><div data-content style={{height:'100%',display:'flex',flexDirection:'column',justifyContent:'center'}}><Content slide={s}/><Foot slide={s}/></div></DeckFrame></section>}
