import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';

const C = {ink:'#102532',paper:'#f8f5ef',coral:'#ff6f61',mint:'#a9efd3',blue:'#b9ddff',yellow:'#ffd98a',white:'#ffffff',muted:'#60707a'};

const segments = [
  {from:0,to:150,text:'小企业做社媒，每个平台都要重新来一次？'},
  {from:150,to:390,text:'把真实产品、客户问题和品牌规则，放进一个 AI 工作流。'},
  {from:390,to:630,text:'AI 先生成 30 天内容日历。'},
  {from:630,to:870,text:'同一个核心信息，改成每个平台的原生版本。'},
  {from:870,to:1050,text:'同一套 Brand Kit，约束海报、轮播和短视频。'},
  {from:1050,to:1230,text:'任务、负责人、截止时间和复盘，进入公司看板。'},
  {from:1230,to:1440,text:'带着自己的业务来，直接做出能用的内容系统。'},
];

const enter = (frame:number, delay=0) => spring({frame:frame-delay,fps:30,config:{damping:18,stiffness:130,mass:.8}});
const Card:React.FC<React.PropsWithChildren<{x?:number;y?:number;rotate?:number;color?:string;width?:number}>>=({children,x=0,y=0,rotate=0,color=C.white,width=820})=>{
  const f=useCurrentFrame(); const p=enter(f,4);
  return <div style={{width,transform:`translate(${x}px,${y+(1-p)*60}px) rotate(${rotate}deg) scale(${.96+.04*p})`,opacity:p,background:color,border:'2px solid rgba(16,37,50,.12)',borderRadius:36,padding:'34px 38px',boxShadow:'0 22px 60px rgba(16,37,50,.13)'}}>{children}</div>;
};
const Tag:React.FC<React.PropsWithChildren<{color?:string}>>=({children,color=C.mint})=><span style={{display:'inline-flex',padding:'10px 18px',borderRadius:999,background:color,fontSize:26,fontWeight:800,margin:'7px'}}>{children}</span>;
const Header:React.FC<{step:string,title:string;sub?:string}>=({step,title,sub})=><div style={{position:'absolute',top:108,left:74,right:74}}><div style={{fontSize:24,fontWeight:900,letterSpacing:3,color:'#c34e44'}}>{step}</div><div style={{fontSize:78,fontWeight:900,lineHeight:1.02,letterSpacing:-4,marginTop:18}}>{title}</div>{sub&&<div style={{fontSize:31,color:C.muted,lineHeight:1.45,marginTop:20}}>{sub}</div>}</div>;

const Hook=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,color:C.ink,padding:74,overflow:'hidden'}}><div style={{position:'absolute',width:680,height:680,borderRadius:'50%',background:C.yellow,top:-310,right:-280}}/><div style={{marginTop:175,fontSize:45,fontWeight:850,color:'#c34e44'}}>小企业做 Social Media</div><div style={{fontSize:106,fontWeight:950,lineHeight:.97,letterSpacing:-7,marginTop:38}}>最浪费时间的<br/>不是写文案</div><div style={{fontSize:54,fontWeight:800,marginTop:46}}>是每个平台都重新来一次。</div><div style={{position:'absolute',bottom:170,left:74,right:74,display:'flex',gap:14,flexWrap:'wrap'}}>{['Instagram','LinkedIn','小红书','视频号','Facebook','YouTube'].map((x,i)=><div key={x} style={{transform:`translateY(${(1-enter(f,i*3))*40}px)`,opacity:enter(f,i*3),fontSize:31,fontWeight:850,padding:'18px 24px',background:i%2?C.white:C.blue,borderRadius:20,border:'2px solid rgba(16,37,50,.12)'}}>{x}</div>)}</div></AbsoluteFill>};

const Inputs=()=> <AbsoluteFill style={{background:C.paper,color:C.ink,padding:74}}><Header step="01 · REAL INPUTS" title="先给 AI 真东西" sub="真实产品、客户问题、品牌规则，缺什么就标记待确认。"/><div style={{position:'absolute',top:610,left:74,right:74,display:'grid',gap:20}}><Card color={C.white}><div style={{fontSize:28,fontWeight:900}}>BUSINESS INPUT</div><div style={{fontSize:46,fontWeight:850,marginTop:16}}>产品 · 价格 · FAQ · 客户原话</div></Card><Card color={C.mint} x={45} rotate={-1.2}><div style={{fontSize:28,fontWeight:900}}>AI WORKFLOW</div><div style={{fontSize:46,fontWeight:850,marginTop:16}}>提取问题 → 组织证据 → 生成 Brief</div></Card><Card color={C.ink} x={10} rotate={1.1}><div style={{color:C.white,fontSize:28,fontWeight:900}}>OUTPUT</div><div style={{color:C.white,fontSize:46,fontWeight:850,marginTop:16}}>Audience Brief + Brand Audit</div></Card></div></AbsoluteFill>;

const Calendar=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:C.paper,color:C.ink,padding:74}}><Header step="02 · CONTENT SYSTEM" title="一次规划 30 天" sub="不是让 AI 随机写 30 条，而是围绕客户问题、证据和 CTA 排产。"/><div style={{position:'absolute',top:650,left:74,right:74}}><Card width={932}><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:12}}>{Array.from({length:20}).map((_,i)=><div key={i} style={{height:90,borderRadius:16,background:[C.mint,C.blue,C.yellow,C.white][i%4],border:'1px solid rgba(16,37,50,.12)',padding:12,opacity:interpolate(f,[i*2,i*2+8],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><div style={{fontSize:19,fontWeight:900}}>{i+1}</div><div style={{width:`${45+(i%3)*18}%`,height:8,background:C.ink,borderRadius:8,marginTop:15,opacity:.35}}/></div>)}</div></Card></div></AbsoluteFill>};

const Platforms=()=> <AbsoluteFill style={{background:C.ink,color:C.white,padding:74}}><Header step="03 · NATIVE ADAPTATION" title="一个核心信息，四种原生表达" sub="事实不变；Hook、结构、CTA 和画面按平台重做。"/><div style={{position:'absolute',top:700,left:74,right:74,display:'grid',gridTemplateColumns:'1fr 1fr',gap:18}}>{[['Instagram','视觉 Hook',C.coral],['LinkedIn','观点 + 证据',C.blue],['小红书','问题 + 清单',C.yellow],['视频号','前三秒 + 字幕',C.mint]].map(([a,b,c])=><Card key={a as string} width={450} color={c as string}><div style={{fontSize:38,fontWeight:950}}>{a}</div><div style={{fontSize:27,fontWeight:750,marginTop:18}}>{b}</div></Card>)}</div></AbsoluteFill>;

const Brand=()=> <AbsoluteFill style={{background:C.paper,color:C.ink,padding:74}}><Header step="04 · BRAND CONSISTENCY" title="设计不再每次换风格" sub="一套 AI Brand Kit 同时约束海报、轮播、短视频和周边。"/><div style={{position:'absolute',top:650,left:74,right:74}}><Card width={932} color={C.white}><div style={{fontSize:29,fontWeight:900}}>AI BRAND KIT</div><div style={{marginTop:22}}><Tag color={C.coral}>Logo</Tag><Tag color={C.mint}>Colour</Tag><Tag color={C.blue}>Type</Tag><Tag color={C.yellow}>Image Style</Tag><Tag color={C.mint}>CTA</Tag></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:14,marginTop:34}}>{['POSTER','CAROUSEL','SHORT VIDEO'].map((x,i)=><div key={x} style={{height:320,borderRadius:24,background:[C.yellow,C.blue,C.coral][i],padding:22,display:'flex',alignItems:'flex-end',fontSize:25,fontWeight:950}}>{x}</div>)}</div></Card></div></AbsoluteFill>;

const Board=()=> <AbsoluteFill style={{background:C.paper,color:C.ink,padding:74}}><Header step="05 · AI BUSINESS OPERATIONS" title="内容进入公司任务系统" sub="负责人、截止时间、阻塞、完成证据，全部可追踪。"/><div style={{position:'absolute',top:660,left:74,right:74,display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:15}}>{[['BACKLOG',C.blue],['DOING',C.yellow],['DONE',C.mint]].map(([t,c],col)=><div key={t as string} style={{background:'rgba(255,255,255,.7)',borderRadius:28,padding:16,minHeight:600,border:'2px solid rgba(16,37,50,.1)'}}><div style={{fontSize:24,fontWeight:950,padding:'8px 6px'}}>{t}</div>{Array.from({length:col===1?3:2}).map((_,i)=><Card key={i} width={250} color={c as string}><div style={{fontSize:23,fontWeight:900}}>{['视觉 QA','平台改写','发布复盘','视频字幕'][i+col]}</div><div style={{fontSize:18,marginTop:20}}>Owner · Due · Evidence</div></Card>)}</div>)}</div></AbsoluteFill>;

const CTA=()=> <AbsoluteFill style={{background:C.ink,color:C.white,padding:74}}><div style={{marginTop:230,fontSize:27,fontWeight:900,letterSpacing:3,color:C.coral}}>JR ACADEMY</div><div style={{fontSize:100,fontWeight:950,lineHeight:.98,letterSpacing:-6,marginTop:36}}>带着自己的<br/>业务来。</div><div style={{fontSize:54,fontWeight:850,lineHeight:1.2,marginTop:70}}>直接做出能用的<br/><span style={{color:C.mint}}>AI 内容系统。</span></div><div style={{position:'absolute',bottom:220,left:74,right:74,padding:'38px 42px',borderRadius:34,background:C.white,color:C.ink}}><div style={{fontSize:38,fontWeight:950}}>小企业 AI 内容营销实战</div><div style={{fontSize:25,color:C.muted,marginTop:12}}>AI Content Marketing for Small Business</div></div></AbsoluteFill>;

const Captions=()=>{const f=useCurrentFrame();const s=segments.find(x=>f>=x.from&&f<x.to);if(!s)return null;return <div style={{position:'absolute',left:70,right:70,bottom:58,display:'flex',justifyContent:'center',zIndex:99}}><div style={{background:'rgba(16,37,50,.92)',color:'#fff',borderRadius:22,padding:'16px 24px',fontSize:30,lineHeight:1.35,fontWeight:800,textAlign:'center',boxShadow:'0 10px 30px rgba(0,0,0,.2)'}}>{s.text}</div></div>};

export const AutomationPromo:React.FC=()=> <AbsoluteFill style={{fontFamily:'Inter,"Noto Sans SC",system-ui,sans-serif'}}><Sequence from={0} durationInFrames={150}><Hook/></Sequence><Sequence from={150} durationInFrames={240}><Inputs/></Sequence><Sequence from={390} durationInFrames={240}><Calendar/></Sequence><Sequence from={630} durationInFrames={240}><Platforms/></Sequence><Sequence from={870} durationInFrames={180}><Brand/></Sequence><Sequence from={1050} durationInFrames={180}><Board/></Sequence><Sequence from={1230} durationInFrames={210}><CTA/></Sequence><Audio src={staticFile('bgm/house-vibez.mp3')} volume={0.08}/><Audio src={staticFile('voice/amy-eleven-v3.mp3')} volume={1}/><Captions/></AbsoluteFill>;

export const Cover:React.FC=()=> <AbsoluteFill style={{background:C.paper,color:C.ink,fontFamily:'Inter,"Noto Sans SC",system-ui,sans-serif',padding:72}}><div style={{position:'absolute',width:680,height:680,borderRadius:'50%',background:C.yellow,top:-330,right:-280}}/><div style={{fontSize:26,fontWeight:900,letterSpacing:3,color:'#c34e44',marginTop:70}}>JR ACADEMY · PRACTICAL COURSE</div><div style={{fontSize:104,fontWeight:950,lineHeight:.96,letterSpacing:-7,marginTop:48}}>AI 自动化<br/>做内容营销</div><div style={{fontSize:38,lineHeight:1.35,fontWeight:800,marginTop:46,maxWidth:850}}>30 天内容日历 · 多平台原生改写<br/>Brand Kit · 短视频 · 公司任务看板</div><div style={{position:'absolute',left:72,right:72,bottom:90,display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14}}>{[['INPUT',C.mint],['CREATE',C.blue],['DESIGN',C.coral],['OPERATE',C.yellow]].map(([x,c])=><div key={x as string} style={{background:c as string,borderRadius:22,padding:'28px 12px',textAlign:'center',fontSize:23,fontWeight:950,border:'2px solid rgba(16,37,50,.12)'}}>{x}</div>)}</div></AbsoluteFill>;
